program: run_training.py
method: bayes
metric:
  name: vals_rmse
  goal: minimize
parameters:
  learning_rate:
    values:
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
  lr_scheduler:
    values:
      - none
      - reduce_on_plateau
  loss:
    values:
      - mse
      - L1
  early_stopping_patience:
    values:
      - 10
      - 20
      - 50

