name: Denoising Autoencoder. MRS Spectra experiment
project_name: Denoising Autoencoder for Coil Combined MRS Spectra
model_name: Denoising Autoencoder
run_name: denoising_autoencoder_transients_individually
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 64 # 64*8 = 512 which makes it comparable to the coil combined spectra
cutoff_training: True
stop_training_after: 128
activation: relu
dropout: 0.2
optimizer: AdamW
patience: 10
diffusion: False
learning_rate: 0.001
predict_noise: False
number_of_transients: 8
loss: L1
epochs: 500
test_batch_size: 32
seed: 42
normalize_input_data: False 
early_stopping_patience: 10
kernel_size : 3
input_channels : 2
output_channels : 64
lr_scheduler: reduce_on_plateau
bn_eps: 0.1
bn_momentum: 0.95
transients: True # loads the transients instead of the coil combined spectra
transients_individually: True # when set to True, will reshape the data from (bs, c, 8, 512) to (bs*8, c, 512)
save_checkpoint_to: models/coil_combined/denoising_autoencoder
save_nifti_in_folder: nifti_files/denoising_autoencoder_l1_transients_individually
save_fitting_results_in_folder: fitting_results/denoising_autoencoder_l1_transients_individually
save_test_results_in_folder: inference_results_numpy_files/denoising_autoencoder_l1_transients_individually