name: CBAM Attention Unet. MRS Spectra experiment
project_name: CBAM Attention Unet for Coil Combined MRS Spectra
model_name:  CBAM Attention Unet 
run_name: cbam_unet_reduce_lr_on_plateau_adamw_kernel_size_3
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
activation: relu
optimizer: AdamW
diffusion: False
test_batch_size: 32
learning_rate: 0.001
predict_noise: False
early_stopping_patience: 10
loss: mse
epochs: 500
seed: 42
kernel_size : 3
input_channels : 2
output_channels : 64
lr_scheduler: reduce_on_plateau 
transients: False
save_checkpoint_to: models/coil_combined/cbam_attention_unet
checkpoint_file_path: models/coil_combined/cbam_attention_unet/last.ckpt
save_nifti_in_folder: nifti_files/cbam_attention_unet
save_fitting_results_in_folder: fitting_results/cbam_attention_unet
save_test_results_in_folder: inference_results_numpy_files/cbam_attention_unet