program: run_training.py
method: bayes
metric:
  name: vals_rmse
  goal: minimize
parameters:
  cyclic_padding_only_at_stem:
    values:
      - True
      - False
    distribution: categorical
  learning_rate:
    max: 0.001
    min: 0.0005
    distribution: uniform
  kernel_size:
    values:
      - 3
      - 5
      - 7
    distribution: categorical
  batch_size:
    values:
      - 32
      - 64
      - 128
  loss:
    values:
      - mse
      - L1
    distribution: categorical
