name: Vanilla Unet. MRS Spectra experiment
project_name: Vanilla Unet for Transients MRS Spectra
model_name: Vanilla Unet
run_name: vanilla_unet_cyclic_padding_only_at_stem_adamw_lr_reduce_on_plateau
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 128
activation: relu
optimizer: AdamW
diffusion: False
learning_rate: 0.001
predict_noise: False
cyclic_padding_only_at_stem: True
loss: mse
test_batch_size: 32
bilinear: False
epochs: 500
seed: 42
normalize_input_data: False 
kernel_size : 3
input_channels : 2
output_channels : 64
lr_scheduler: reduce_on_plateau 
transients: True
save_checkpoint_to: models/transients/vanilla_unet
checkpoint_file_path: models/transients/vanilla_unet/last.ckpt
save_nifti_in_folder: nifti_files/vanilla_unet_transients
save_fitting_results_in_folder: fitting_results/vanilla_unet_transients