name: Denoising Autoencoder. MRS Spectra experiment
project_name: Denoising Autoencoder for Transients MRS Spectra
description: Denoising Autoencoder for MRS Spectra experiment
model_name: Denoising Autoencoder
run_name: denoising_autoencoder_transients_patience_10_lr_reduce_on_plateau_adamw
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
activation: relu
dropout: 0.2
optimizer: AdamW
diffusion: False
learning_rate: 0.001
predict_noise: False
loss: L1
test_batch_size: 32
early_stopping_patience: 10
epochs: 500
seed: 42
kernel_size : 3
input_channels : 2
output_channels : 64
lr_scheduler: reduce_on_plateau 
bn_eps: 0.1
bn_momentum: 0.95
transients: True
save_checkpoint_to: models/transients/denoising_autoencoder
checkpoint_file_path: models/transients/denoising_autoencoder/last.ckpt
save_nifti_in_folder: nifti_files/denoising_autoencoder_transients
save_fitting_results_in_folder: fitting_results/denoising_autoencoder_transients