name: Denoising CNN with skip connection. MRS Spectra experiment
project_name: DnCNN original with skip connection for Coil Combined MRS Spectra
model_name: DnCNN with skip connection
run_name: dncnn_full_dataset_500_epochs_patience_10_reduce_lr_plateau_adamw
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
activation: relu
dropout: 0.2
depth: 17
optimizer: AdamW
diffusion: False
learning_rate: 0.0013676595054837974
lr_decay: 1.217850676291086
lr_scheduler: reduce_on_plateau
bn_eps: 0.12723797538462123
bn_momentum: 1.2708869851276277
predict_noise: True
test_batch_size: 32
loss: mse
epochs: 500
seed: 42
normalize_input_data: False 
kernel_size : 3
input_channels : 2
output_channels : 64
transients: False
save_checkpoint_to: models/coil_combined/dncnn/dncnn_original
checkpoint_file_path: models/coil_combined/dncnn/dncnn_original/last.ckpt
save_nifti_in_folder: nifti_files/dncnn_original
save_fitting_results_in_folder: fitting_results/dncnn_original
save_test_results_in_folder: inference_results_numpy_files/dncnn