program: run_training.py
method: bayes
metric:
  name: vals_rmse
  goal: minimize
parameters:
  learning_rate:
    values:
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
  lr_scheduler:
    values:
      - none
    distribution: categorical
  kernel_size:
    values:
      - 3
      - 5
      - 7
    distribution: categorical
  batch_size:
    values:
      - 64
      - 128
      - 256
      - 512
    distribution: categorical
  loss:
    values:
      - mse
      - L1
    distribution: categorical

