name: Vanilla Unet. MRS Spectra experiment
project_name: Vanilla Unet for Coil Combined MRS Spectra
model_name: Vanilla Unets
run_name: vanilla_unet_patience_10_lr_reduce_on_plateau_adamw
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
activation: relu
optimizer: AdamW
diffusion: False
learning_rate:  0.001
predict_noise: False
loss: mse
bilinear: False
test_batch_size: 32
epochs: 500
seed: 42
normalize_input_data: False 
kernel_size : 3
input_channels : 2
output_channels : 64
lr_scheduler: reduce_on_plateau 
transients: False
save_checkpoint_to: models/coil_combined/vanilla_unet
checkpoint_file_path: models/coil_combined/vanilla_unet/last.ckpt
save_nifti_in_folder: nifti_files/vanilla_unet
save_fitting_results_in_folder: fitting_results/vanilla_unet
save_test_results_in_folder: inference_results_numpy_files/vanilla_unet