name: Diffusion Unet with CBAM and Resblock MRS Spectra experiment
project_name: Diffusion Unet with CBAM and Resblock for Coil Combined MRS Spectra
model_name: Diffusion Unet with CBAM and Resblock
run_name: diffusion_unet_cbam_resblock
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
learning_rate: 0.0001
cutoff_training: False
loss: mse
epochs: 500
seed: 42
kernel_size : 3
input_channels : 2
output_channels : 64
test_batch_size: 32
transients: False
input_size: 512 # spectral length
diffusion: True
predict_noise: False
early_stopping_patience: 10
time_embedding_mlp: True
beta_small: 0.0001 # cannot be 1e-4
beta_large: 0.02
diffusion_steps: 1000
diffusion_beta_schedule: linear
conditional: True
beta_offset: 0.008 
save_checkpoint_to: models/coil_combined/diffusion/ddpm_resblock
checkpoint_file_path: models/coil_combined/diffusion/ddpm_resblock/last.ckpt
save_nifti_in_folder: nifti_files/diffusion_unet_resblock
save_fitting_results_in_folder: fitting_results/diffusion_unet_resblock
save_test_results_in_folder: inference_results_numpy_files/diffusion_unet_resblock