name: Fully Connected DenseNet. MRS Spectra experiment
project_name: Fully Connected DenseNet for Coil Combined MRS Spectra
model_name: Fully Connected DenseNet
run_name: fc_densenet_fill_dataset_500_epochs_patience_10_reduce_lr_plateau_adamw
data_value: real
train_split: 0.7
val_split: 0.2
test_split: 0.1
batch_size: 512
activation: relu
optimizer: AdamW
diffusion: False
learning_rate:  0.001
test_batch_size: 32
lr_scheduler: reduce_on_plateau
lr_decay: 0.995
test_batch_size: 32
predict_noise: False
loss: mse
epochs: 500
seed: 42
kernel_size : 3
input_channels : 2
output_channels : 64
transients: False
save_checkpoint_to: models/coil_combined/fully_connected_unet
checkpoint_file_path: models/coil_combined/fully_connected_unet/last.ckpt
save_nifti_in_folder: nifti_files/fully_connected_unet
save_fitting_results_in_folder: fitting_results/fully_connected_unet
save_test_results_in_folder: inference_results_numpy_files/fc_densenet